name: Waka Readme

on:
workflow_dispatch:
  schedule:
    # Runs at 12am IST
    - cron: "30 18 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: dreywesson/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
